_reference_jdk: &reference_jdk
 'JDK="adopt@1.8"'
_reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
  autocrlf: input

os:
  - osx
  - windows
  - *reference_os
addons:
  apt:
    packages:
      - graphviz

stages:
  - check
  - test
  - name: deploy
    if: repo = DanySK/listset AND type != pull_request

env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@"
    - JDK="adopt-openj9@"

jobs:
  exclude:
    - stage: test
      os: *reference_os
      env: *reference_jdk
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
    - stage: deploy
      name: "Reports and deployment"
      os: *reference_os
      env:
        - PUBLISH="true"
        # Signing
        - secure: "AAsdBhoPJk3GbsNP7+bMQLkflGPNLsE32yg3dHT1lrGfknzXP+6Aurrn06TunA3DzDcfYOZFVED1OiUaGPY8UOOC/mMeNHm6cQUeBDdMoodQWwFFenQ9DqbtZu+863+05BdqTgQiHH0boMBs98qEQW0DBLk8hBgfvaxrNXLI5VvLpRUe5R2TM70tDjJWqm/S7RD/cLg08IFhtg0hSccPp/d/QnslBAldsBWqNDO3JHvMDMS++9UUr9YaDqzoNFz7pIERK8rsRavSqcCzKKHvceUIHr4cHrdauPP1apUVEa1vre4zNMxqG67BhBdIQAPAl8qUKHGzfHPus6tEcbroe6Vfoul9aLqvrrq1G8+zuYJNkj5Vw4ovYAe8DhUnQ19rmlt5UECklRwsPhgybbCrO+rvJOfXVyuNB2pC0Kbj7xthi3WnEfrh09srYAVQQa+jwUTnOeKcv1w+qr7I8jJhJDpKtRbBtduLexT+SRJLs7U40ul+BHUqb/+sdhskV+kcDDQPrZffzvcTjooUup+Zr+BQrayXKkGcULyDJjYeQzJBrgvD9d9beg/RTdjufHcksyNXHVSwbcDOZnh02UO0UXBNyoz3U72e8Y3pq0TRh4MWXJydWZFWAPxbWnJY3AyeaqGmkdzVjn3Z84zzIV9pg+H4o7zGUhsvvJjvNRIJzC8="
        # Central
        - secure: "PIxf6SFrhB5y7JRca/7nc8/mp6ecbmboHA7aLIy72iaJCdwo3zBONxHdwZNTRbTRm7HP2bp6vs84Y7IcsmhOi7na/nods+guO4WYy/UUioPxkQBd4ba67KBR2rFeVlfJMqQZhudu7WuPySKnctYN3qiAky2nnOwNJElIqvHia8qUN/Qkj7tVCSI5b5X1KYfSVhWyP7oaVhf+0kJEtbdCgkSUj7sOIg2eJqhg7HhkeueqVoYP7y5/kyn99XP4vs6q9bGOEUoPIiggWZA/wxUtvxeQFLl6gp21DUQjrD/7WhBZYKrRnH2aRqd0IkxT3ZC51T4j3tP/JUum6tdqm4kYJRzefa+BynEFPBQq4grZL1angUJqY/8yU2eh9LalhhXWH40htGR4/t6+sCR7LGVgaG2PXjo1duJN89+6lKuv2+ypTQ42C2i3Zy/AR9UIBL7PQkSHtA/zoT59IZc9/Sy9GgpRMhT+h1Kw3Ufb1YPe9JdL/uJeN7kc7Zn303Z4r2SolWFBvhNxRIR/LrySivBLhAEmV0lDBH+eQyMFIEN9XJRZ4KTVjf8Bv/6Hr8bPzp+RS8s+lrfQoMojuKUwK8bEOf8d8PMzRLSGB/rLaZLVv3AS6o/r6MAy90YtdRDBMxSDEG4qPb6AAAMLVFSFr0nIjDHWdUsVnEsD9985vAIO7IA="
        - secure: "N+VjC0GtJ2IGiXZ88tJJQZys/K8dpen2FiEQXY1eZtRDIdRQ6ew5+ZVkrDOoNTVu82bRUBPU9hWkTBVkYArGQT+OwL0ApG0qWBNTJLa76ptHxcU1dsFM9Wqp82ErjXyrD0fV9SieQ1nvmC5RzwG7AXaqBEFNq1r8Auw69huxytLMFQRcHn1UR7LLY1HkDuApztb5lHL3Jz2kf/yV1tsFOFgcXGwEeSgRL3aN3tJIz2CDr1b0AeJV3e8TBeY4GLD5KNMFLdER8uQIQh+3+nJ1L/03TYT07giDKBevyqAjREUGHVRoQFIVSmPHa6ZibRp+gS+a2rBmfkkY1rNYAHlxGvvK8gAxQNoo2QlQk+0v3n1SxsOVtNE+r4l1u2VfkoNVcNm25uznkD0nAQWLSrUAc2SyTfknkrnRvKRO4sPuDj6jcoP9u80GMs7i0Ji2HHMURm9C/3fNwonWCnY1RRNF2Cc058S0V2ceGJ0cHIrLUCOOubBIEizI3lsDI/dp+Km3v2MCIqd7TmhEW5AJD3y9dBHH67bTL7TPw6crfFwXmCJJbpXS1zoNF4+I8hz/5Wy3gHzVzTEIy9P/LE/8fTiPj6HN9xPVw4O44q04CdWU/e9i++1AT4jvHyhFVNurBtAGuCKAIGqr6A52dddq3btF2QT+S8FbzAn7O9NBYDsJIzw="
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_0f1727a4905b_key -iv $encrypted_0f1727a4905b_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - travis_retry ./gradlew publishAllPublicationsToMavenRepository

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script:
  - travis_retry ./gradlew check

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
